
  sudo: required
  services:
    - docker
    - redis-server
  language: ruby
  cache:
    bundler: true
    yarn: true
    directories:
      - node_modules
  addons:
    postgresql: "9.6"
    chrome: stable
  rvm:
    - 2.5.1
  install:
    - bundle install
    - nvm install node
    - node -v
    - npm i -g yarn
    - yarn install
  before_script:
    - cp config/database.yml.travis config/database.yml
    - psql -c 'create database travis_ci_test;' -U postgres
    - bundle exec rake db:create db:test:prepare
  script:
    - yarn test
    - bundle exec rspec spec
  after_success:
    - bundle exec rake assets:precompile