addons:
  postgresql: 9.6
  code_climate:
      repo_token: <Get from Code Climate>
before_install:
  - gem update --system
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database lorecharacters_test;' -U postgres
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
dist: trusty
language: ruby
rvm:
  - 2.5.3
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
  - bin/yest
services:
  - redis-server